openapi: 3.0.3
info:
  title: Home Devices QoD
  description: |-
    Service Enabling Network Function API for *QoS-on-demand* (QoD) control applied to devices connected to the user home network. API clients can request to change, on demand, the desired QoS behaviour for the IP traffic corresponding to a specific user home device. The QoS behaviour is determined by the Service Class provided by the API Client, which is mapped to a DSCP value according to [RFC4594](https://datatracker.ietf.org/doc/html/rfc4594) guidelines.

    # Relevant Definitions and concepts

    - **Home Devices**: User devices connected to the user home network.
    - **NaaS**: *Network-as-a-Service* model where Telco Network resources are exposed to third parties through APIs. In this particular API, QoD operations for home devices are exposed following this model.
    - **Service Class**: A statement of the required QoS characteristics of a traffic aggregate. Conceptually, a service class refers to applications with similar characteristics and performance requirements.
    - **DSCP**: *Differentiated Services (DiffServ) Code Point*. DiffServ is a simple and scalable mechanism for classifying and managing network traffic and providing quality of service (QoS) on IP networks. The DSCP value will be used to classify the traffic of the target home device in order to be treated accordingly. 

    # API Functionality

    This API allows to third party clients to set, on demand, the desired QoS behaviour (service class) associated to the traffic of the device connected to the user home network that matches the input criteria provided. The device traffic is classified (by DSCP) and treated accordingly.
     
    - **NOTE: This API allows QoS treatment to be applied to a target user device only within the user Home Network (i.e. between the device and the home router)**.

    # Resources and Operations overview

    The API provides a single endpoint:
     
    - An endpoint to set the desired QoS behaviour for the traffic corresponding to the user home device matching the input criteria.
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.2.0
servers:
  - url: https://{host}{basePath}
    variables:
      host:
        default: api.example.com
        description: Host that serves the API
      basePath:
        default: /home-devices-qod/v0
        description: API URL prefix for all API paths
paths:
  /qos:
    put:
      summary: Set the desired QoS behaviour for a user home device
      description: |-
        Set the desired QoS behaviour for the traffic corresponding to the user home device matching the input criteria. **QoS behaviour is determined by the service class provided by the API Client. Setting `standard` service class restores default traffic treatment for the target home device.**
        
        - The operation is executed for the user whose `sub` is in the access token used to call this endpoint, and for the home network also deducted from the information included in the access token.
        - The target user device is identified by the internal IP address of that device in the home network.
        - In case there is no device matching the input criteria, the operation returns a 404 error.
      tags:
        - Home Devices QoD
      operationId: setQos
      parameters:
        - $ref: '#/components/parameters/x-correlator'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QosOnDemandUpdate'
            example: 
              serviceClass: real_time_interactive
              ipAddress: 192.168.1.27
        required: true
      responses:
        '204':
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          description: Requested QoS passed all validations and was applied
        '400':
          $ref: '#/components/responses/Error400InvalidArgument'
        '401':
          $ref: '#/components/responses/Error401Unauthenticated'
        '403':
          $ref: '#/components/responses/setQosPermissionDenied'
        '404':
          $ref: '#/components/responses/setQosNotFound'
        '409':
          $ref: '#/components/responses/setQosConflict'
        '500':
          $ref: '#/components/responses/Error500Internal'
        '503':
          $ref: '#/components/responses/setQosServiceUnavailable'
        '504':
          $ref: '#/components/responses/Error504Timeout'
components:
  schemas:
    QosOnDemandUpdate:
      type: object
      description: Payload to change the QoS behaviour associated to a device.
      required:
        - serviceClass
        - ipAddress
      properties:
        serviceClass:
          type: string
          description: |-
            The name of the service class requested by the API client. It is associated with QoS behaviours optimised for a particular application type. Each service class is mapped to a DSCP value according to [RFC4594](https://datatracker.ietf.org/doc/html/rfc4594) guidelines. The DSCP value is used to classify the target home device's traffic so that it can be treated accordingly (i.e. to meet its QoS needs).
            
            The following service classes are supported:

            | Service Class Name    | DSCP Name | DSCP value (decimal) | DCSP value (binary) | Application Examples                          |
            |-----------------------|-----------|----------------------|---------------------|-----------------------------------------------|
            | Real-Time Interactive |    CS4    |          32          |        100000       | Video conferencing and Interactive gaming     |
            | Multimedia Streaming  |    AF31   |          26          |        011010       | Streaming video and audio on demand           |
            | Broadcast Video       |    CS3    |          24          |        011000       | Broadcast TV & live events                    |
            | Low-Latency Data      |    AF21   |          18          |        010010       | Client/server transactions Web-based ordering |
            | High-Throughput Data  |    AF11   |          10          |        001010       | Store and forward applications                |
            | Low-Priority Data     |    CS1    |           8          |        001000       | Any flow that has  no BW assurance            |
            | Standard              |  DF(CS0)  |           0          |        000000       | Undifferentiated applications                 |
          enum:
            - real_time_interactive
            - multimedia_streaming           
            - broadcast_video
            - low_latency_data
            - high_throughput_data
            - low_priority_data
            - standard
          example: real_time_interactive 
        ipAddress:
          type: string
          format: ipv4
          pattern: '^([01]?\d\d?|2[0-4]\d|25[0-5])(?:\.(?:[01]?\d\d?|2[0-4]\d|25[0-5])){3}?$'
          description: Internal IP address of the connected device in the LAN.
          example: 192.168.1.27
    ErrorInfo:
      type: object
      required:
        - status
        - code
        - message
      properties:
        status:
          type: integer
          description: HTTP status code returned along with this error response
        code:
          type: string
          description: A code value within the allowed set of values for this error
        message:
          type: string
          description: A human readable description of what the event represents
  responses:
    Error400InvalidArgument:
      description: Problem with the client request
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          examples:
            InvalidArgument:
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param
    Error401Unauthenticated:
      description: Authentication problem with the client request
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          examples:
            Unauthenticated:
              value:
                status: 401
                code: UNAUTHENTICATED
                message: Request not authenticated due to missing, invalid, or expired credentials
    setQosPermissionDenied:
      description: |-
        Client does not have sufficient permission.
        In addition to regular PERMISSION_DENIED scenario another scenario may exist:
          - User home network cannot be deducted from access token context.("code": "HOME_DEVICES_QOD.INVALID_TOKEN_CONTEXT","message": "User home network cannot be deducted from access token context.").
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          examples:
            PermissionDenied:
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action
            InvalidTokenContext:
              value:
                status: 403
                code: HOME_DEVICES_QOD.INVALID_TOKEN_CONTEXT
                message: User home network cannot be deducted from access token context
    setQosNotFound:
      description: |-
        Resource Not Found.
        In addition to regular scenario of NOT_FOUND, another scenario may exist.
         - There is no device matching the input criteria. ("code": "HOME_DEVICES_QOD.NO_DEVICE_MATCH","message": "No connected device found for the input criteria provided.").
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          examples:
            NotFound:
              value:
                status: 404
                code: NOT_FOUND
                message: The specified resource is not found
            NoDeviceMatch:
              value:
                status: 404
                code: HOME_DEVICES_QOD.NO_DEVICE_MATCH
                message: No connected device found for the input criteria provided
    setQosConflict:
      description: |-
        Requested QoS can't be set. 
        
        In addition to regular CONFLICT scenario to handle conflict with the current state of the target resource, another scenarios may exist:
         - HOME_DEVICES_QOD.TOO_MANY_DEVICES: Exceeded the maximum quantity of devices with non-default QoS behaviour.
         - HOME_DEVICES_QOD.RSSI_BELOW_THRESHOLD: RSSI from device is below allowed threshold.
         - HOME_DEVICES_QOD.QOS_TOO_HIGH: Requested QoS is higher than the maximum QoS allowed.
         - HOME_DEVICES_QOD.OCCUPANCY_ABOVE_THRESHOLD: The occupancy is above the allowed threshold.
         - HOME_DEVICES_QOD.NOT_CONNECTED_TO_REQUIRED_INTERFACE: Device is not connected to the required interface (e.g. WiFi 5GHz interface).
         - HOME_DEVICES_QOD.NOT_SUPPORTED_REQUIRED_INTERFACE: Device does not support required interface (e.g. WiFi 5GHz interface).
         - HOME_DEVICES_QOD.QOS_ALREADY_SET_TO_DEFAULT: Device QoS is already set to default value.
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          examples:
            Conflict:
              value:
                status: 409
                code: CONFLICT
                message: Conflict with the current state of the target resource
            TooManyDevices:
              value:
                status: 409
                code: HOME_DEVICES_QOD.TOO_MANY_DEVICES
                message: Exceeded the maximum quantity of devices with non-default QoS behaviour
            RssiBelowThreshold:
              value:
                status: 409
                code: HOME_DEVICES_QOD.RSSI_BELOW_THRESHOLD
                message: RSSI from device is below allowed threshold
            QosTooHigh:
              value:
                status: 409
                code: HOME_DEVICES_QOD.QOS_TOO_HIGH
                message:  Requested QoS is higher than the maximum QoS allowed
            OccupancyAboveThreshold:
              value:
                status: 409
                code: HOME_DEVICES_QOD.OCCUPANCY_ABOVE_THRESHOLD
                message: The occupancy is above the allowed threshold
            NotConnectedToRequiredInterface:
              value:
                status: 409
                code: HOME_DEVICES_QOD.NOT_CONNECTED_TO_REQUIRED_INTERFACE
                message: Device is not connected to the required interface (e.g. WiFi 5GHz interface)
            NotSupportedRequiredInterface:
              value:
                status: 409
                code: HOME_DEVICES_QOD.NOT_SUPPORTED_REQUIRED_INTERFACE
                message: Device does not support required interface (e.g. WiFi 5GHz interface)
            QosAlreadySetToDefault:
              value:
                status: 409
                code: HOME_DEVICES_QOD.QOS_ALREADY_SET_TO_DEFAULT
                message: Device QoS is already set to default value
    Error500Internal:
      description: Server error
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          examples:
            Internal:
              value:
                status: 500
                code: INTERNAL
                message: Server error
    setQosServiceUnavailable:
      description: |-
        Service unavailable. Typically the server is down.
        
        In addition to regular scenario of UNAVAILABLE to handle service availability problems, another scenario may exist.
         - The router is offline ("code": "HOME_DEVICES_QOD.ROUTER_OFFLINE","message": "Router is not online. Try it later.").
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          examples:
            Unavailable:
              value:
                status: 503
                code: UNAVAILABLE
                message: Request timeout exceeded
            RouterOffline:
              value:
                status: 503
                code: HOME_DEVICES_QOD.ROUTER_OFFLINE
                message: Router is not online. Try it later
    Error504Timeout:
      description: Request time exceeded. If it happens repeatedly, consider reducing the request complexity
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          examples:
            Timeout:
              value:
                status: 504
                code: TIMEOUT
                message: Request timeout exceeded
  parameters:
    x-correlator:
      name: x-correlator
      in: header
      description: Correlation id for the different services
      schema:
        type: string
  headers:
    x-correlator:
      description: Correlation id for the different services
      schema:
        type: string
  securitySchemes:
    three_legged:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
security:
  - three_legged:
    - home-devices-qod-qos-write
tags:
  - name: Home Devices QoD
    description: QoD control operations for home devices
externalDocs:
  description: Project documentation at CAMARA
  url: https://github.com/camaraproject/
